### ISSUE TITLE
Script to update and down grade nats server versions

### ISSUE THREAD

**Issue by gedw99** [synadia-labs/eventually-consistent-virtual-global-stream#3]
This is excellent and thank you  for making this and the excellent article explaining the theory.

Another reality of running a nats system is doing upgrades with no downtime by utilising the excellent “lame duck” mode that nats thankfully has.

this can be done with a set of scripts to perform upgrades in the correct way via orchestration.

Clients will still be able to perform their normal operations whilst the upgrade is occurring .

**Comment by jnmoyne** [comment]
Thanks for your words of appreciation. Closing this as it is more of a comment than a question needing an answer :).
